name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

# env:
#   ECR_NAME: ${{ secrets.ECR_NAME }}
#   KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
#   KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t foo .
